from . import assignment
from . import assignment_submission
from . import attendance_staff
from . import attendance_student
from . import examination
from . import examination_result
from . import grade_range
from . import grading_system
from . import lesson_plan
from . import report_card_template
from . import school_class
from . import section
from . import student
from . import subject
from . import syllabus_tracker
from . import id_card_template

from . import employee
from . import department
from . import job_position
from . import employee_leave
from . import leave_type
from . import appraisal
from . import payroll
from . import salary_component
from . import employee_payroll

from . import fee_category
from . import fee_structure
from . import fee_assignment
from . import fee_invoices
from . import fee_invoices_line
from . import fee_payment
from . import fee_remainder

from . import transport_route
from . import transport_stop
from . import transport_vehicle
from . import transport_assignment

from . import hostel_building
from . import hostel_room
from . import hostel_fee
from . import hostel_allocation

from . import library_category
from . import library_book
from . import library_issues
from . import library_fine

from . import inventory_category
from . import inventory_item
from . import purchase_order
from . import purchase_order_line

from . import document_type
from . import document_upload
from . import online_admission
from . import e_learning_module
from . import e_learning_course
from . import e_learning_activity
from . import e_learning_answer
from . import e_learning_content
from . import e_learning_progress
from . import e_learning_question
from . import e_learning_quiz

from . import academic_term
from . import academic_year
from . import alumni
from . import alumni_event
from . import alumni_event_registration
from . import certificate_template
from . import certificate_issue
from . import discipline_category
from . import discipline_incident
from . import global_setting
from . import school_branch
from . import school_event
from . import school_calander

from . import message
from . import message_recipient
from . import notice
from . import newsletter
from . import portal_user
from . import portal_access_group
from . import portal_access_right
from . import portal_user_group
from . import mobile_app_setting
from . import  notification_template
from . import email_configuration
from . import sms_configuration
from . import push_notification
from . import report_template
from . import report_field
from . import report_filter
from . import custom_report
from . import dashboard_widget