{
    "name":"School Management",
    "version":"1.0",
    "summary":"This is about the School Management Project",
    "author":"Jvl Techonologies",
    "category":"School Management",
    "depends":['base',"web"],
    "data":[
        "security/ir.model.access.csv",
        "views/fee_assignment.xml",
        'views/fee_category.xml',
        'views/fee_invoice.xml',
        'views/fee_structure.xml',
        'views/fee_remainder.xml',
        'views/appraisal.xml',
        'views/department.xml',
        'views/employee.xml',
        'views/employee_leave.xml',
        'views/employee_payroll.xml',
        'views/fee_invoices_line.xml',
        'views/hostel_allocation.xml',
        'views/hostel_building.xml',
        'views/hostel_fee.xml',
        'views/hostel_room.xml',
        'views/fee_payment.xml',
        'views/message.xml',
        'views/message_recipient.xml',
        'views/notice.xml',
        'views/newsletter.xml',
        'views/portal_user.xml',
        'views/portal_access_group.xml',
        'views/portal_access_right.xml',
        'views/portal_user_group.xml',
        'views/mobile_app_setting.xml',
        'views/notification_template.xml',
        'views/email_configuration.xml'

    ],
    'assets':{

    },
    "installable":True,
    "application":True,

}